import { NestFactory } from '@nestjs/core';
import { getModelToken } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { AppModule } from '../app.module';
import { Batch } from '../batches/schemas/batch.schema';
import { Branch } from '../branches/schemas/branch.schema';
import {
  MovementType,
  StockMovement,
} from '../inventory/schemas/stock-movement.schema';
import { Product } from '../products/schemas/product.schema';
import { Supplier } from '../suppliers/schemas/supplier.schema';
import { User } from '../users/schemas/user.schema';

type NotebookItem = {
  lineNumber: number;
  section: string;
  name: string;
  brand: string;
  strength: string;
  unit?: string;
  form?: 'ampoule' | 'vial' | 'bottle' | 'tablet' | 'strip' | 'piece' | 'box' | 'cup' | 'kit' | 'tube' | 'device';
  route: string;
  quantity: number;
  expiry: string;
  category: 'prescription' | 'otc' | 'vitamins' | 'diagnostics' | 'supplies' | 'equipment' | 'consumables';
  requiresPrescription: boolean;
  needsReview?: boolean;
  reviewNote?: string;
};

const NOTEBOOK_IMPORT_SUPPLIER = {
  name: 'Manual Notebook Import Supplier',
  contactPerson: 'Notebook Stock Entry',
  phone: '+232-00-000-000',
  email: 'notebook.import@carefarm.example',
  address: 'Manual inventory notebook import',
  paymentTerms: 'Pending confirmation',
  isActive: true,
};

const notebookItems: NotebookItem[] = [
  {
    lineNumber: 1,
    section: 'injection-primary',
    name: 'Tranexamic Acid Injection',
    brand: 'American Remedies',
    strength: '500mg/5ml',
    form: 'ampoule',
    route: 'IV',
    quantity: 300,
    expiry: '2027-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 2,
    section: 'injection-primary',
    name: 'Tranexamic Acid Injection',
    brand: 'A-Tranex',
    strength: '500mg/5ml',
    form: 'ampoule',
    route: 'IV',
    quantity: 10,
    expiry: '2028-01',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 3,
    section: 'injection-primary',
    name: 'Tranexamic Acid Injection',
    brand: 'M-Tramic',
    strength: '500mg/5ml',
    form: 'ampoule',
    route: 'IV',
    quantity: 200,
    expiry: '2027-01',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 4,
    section: 'injection-primary',
    name: 'Magnesium Sulfate Injection',
    brand: 'Unknown',
    strength: '500mg/ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 200,
    expiry: '2028-06',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 5,
    section: 'injection-primary',
    name: 'Piperacillin and Tazobactam Injection',
    brand: 'Unknown',
    strength: '4.5g',
    form: 'vial',
    route: 'IV',
    quantity: 65,
    expiry: '2027-12',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 6,
    section: 'injection-primary',
    name: 'Clindamycin Injection',
    brand: 'Unknown',
    strength: '600mg/4ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 167,
    expiry: '2027-10',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 7,
    section: 'injection-primary',
    name: 'Clindamycin Injection',
    brand: 'Unknown',
    strength: '300mg',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 67,
    expiry: '2028-02',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 8,
    section: 'injection-primary',
    name: 'Vancomycin Hydrochloride Injection',
    brand: 'Unknown',
    strength: '1g',
    form: 'vial',
    route: 'IV',
    quantity: 87,
    expiry: '2027-09',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 9,
    section: 'injection-primary',
    name: 'Vancomycin Hydrochloride Injection',
    brand: 'ASH-Vanco',
    strength: '1g',
    form: 'vial',
    route: 'IV',
    quantity: 1,
    expiry: '2027-06',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 10,
    section: 'injection-primary',
    name: 'Amphotericin B Injection',
    brand: 'Unknown',
    strength: '50mg',
    form: 'vial',
    route: 'IV',
    quantity: 30,
    expiry: '2027-01',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 11,
    section: 'injection-primary',
    name: 'Amikacin Sulfate Injection',
    brand: 'Unknown',
    strength: '500mg/2ml',
    form: 'ampoule',
    route: 'IV/IM',
    quantity: 25,
    expiry: '2027-01',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 12,
    section: 'injection-primary',
    name: 'Vitamin K3 Injection',
    brand: 'Unknown',
    strength: '25mg/2ml',
    form: 'ampoule',
    route: 'IM',
    quantity: 40,
    expiry: '2027-10',
    category: 'vitamins',
    requiresPrescription: true,
  },
  {
    lineNumber: 13,
    section: 'injection-primary',
    name: 'Paracetamol Injection',
    brand: 'Unknown',
    strength: '300mg/2ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 60,
    expiry: '2028-02',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 14,
    section: 'injection-primary',
    name: 'Gentamicin Injection',
    brand: 'Unknown',
    strength: '80mg/2ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 50,
    expiry: '2028-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 15,
    section: 'injection-primary',
    name: 'Furosemide Injection',
    brand: 'Petamide',
    strength: '20mg',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 58,
    expiry: '2026-08',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 16,
    section: 'injection-primary',
    name: 'Furosemide Injection',
    brand: 'Fumide',
    strength: '20mg/2ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 40,
    expiry: '2028-03',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 17,
    section: 'injection-primary',
    name: 'Metoclopramide Injection',
    brand: 'Top Pros',
    strength: '10mg/2ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 80,
    expiry: '2028-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 18,
    section: 'injection-primary',
    name: 'Ergometrine Injection',
    brand: 'Unknown',
    strength: 'Unspecified',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 70,
    expiry: '2028-06',
    category: 'prescription',
    requiresPrescription: true,
    needsReview: true,
    reviewNote: 'Strength is not visible in the provided image.',
  },
  {
    lineNumber: 19,
    section: 'injection-primary',
    name: 'Ephedrine Injection',
    brand: 'Unknown',
    strength: '50mg/1ml',
    form: 'ampoule',
    route: 'Injection',
    quantity: 30,
    expiry: '2026-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 20,
    section: 'injection-primary',
    name: 'Vecuronium Bromide Injection',
    brand: 'Unknown',
    strength: '4mg',
    form: 'vial',
    route: 'Injection',
    quantity: 10,
    expiry: '2028-01',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 21,
    section: 'injection-primary',
    name: 'Naloxone Injection',
    brand: 'Unknown',
    strength: '1ml',
    form: 'ampoule',
    route: 'Injection',
    quantity: 8,
    expiry: '2027-08',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 22,
    section: 'injection-primary',
    name: 'Aminophylline Injection',
    brand: 'Unknown',
    strength: '250mg/10ml',
    form: 'ampoule',
    route: 'Injection',
    quantity: 79,
    expiry: '2029-08',
    category: 'prescription',
    requiresPrescription: true,
    needsReview: true,
    reviewNote: 'Expiry is inferred from unclear handwriting in the newer image.',
  },
  {
    lineNumber: 1,
    section: 'medicine-secondary',
    name: 'T-B Strips',
    brand: 'Namo Care',
    strength: '',
    unit: 'strip',
    route: 'N/A',
    quantity: 35,
    expiry: '2028-06',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 1,
    section: 'medicine-secondary',
    name: 'T-B',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 2,
    expiry: '2026-08',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Item description is abbreviated as T-B only in the notebook.',
  },
  {
    lineNumber: 2,
    section: 'medicine-secondary',
    name: 'Ampiclox Syrup',
    brand: 'Unknown',
    strength: '60ml',
    unit: 'bottle',
    route: 'Oral',
    quantity: 79,
    expiry: '2027-09',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 3,
    section: 'medicine-secondary',
    name: 'Zinc Sulphate Tablets',
    brand: 'Unknown',
    strength: '20mg',
    unit: 'tablet',
    route: 'Oral',
    quantity: 990,
    expiry: '2028-07',
    category: 'otc',
    requiresPrescription: false,
  },
  {
    lineNumber: 4,
    section: 'medicine-secondary',
    name: 'Nifedipine Tablets',
    brand: 'Unknown',
    strength: '20mg',
    unit: 'tablet',
    route: 'Oral',
    quantity: 0,
    expiry: '2099-12',
    category: 'prescription',
    requiresPrescription: true,
    needsReview: true,
    reviewNote: 'Quantity and expiry were not visible in the notebook; placeholder values used.',
  },
  {
    lineNumber: 23,
    section: 'medicine-secondary',
    name: 'Methotrexate Injection',
    brand: 'Zhvitrex',
    strength: '50mg/2ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 30,
    expiry: '2027-02',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 24,
    section: 'medicine-secondary',
    name: 'Methotrexate Injection',
    brand: 'Plastomet-50',
    strength: '50mg/2ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 4,
    expiry: '2028-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 25,
    section: 'medicine-secondary',
    name: 'Propofol Injection',
    brand: 'Unknown',
    strength: '200mg/20ml',
    form: 'ampoule',
    route: 'Injection',
    quantity: 0,
    expiry: '2027-06',
    category: 'prescription',
    requiresPrescription: true,
    needsReview: true,
    reviewNote: 'Quantity was not visible in the image.',
  },
  {
    lineNumber: 26,
    section: 'medicine-secondary',
    name: 'Dactinomycin Injection',
    brand: 'Unknown',
    strength: '0.5mg',
    form: 'vial',
    route: 'Injection',
    quantity: 5,
    expiry: '2024-09',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 27,
    section: 'medicine-secondary',
    name: 'Potassium Chloride Injection',
    brand: 'Unknown',
    strength: '10%',
    form: 'ampoule',
    route: 'IV',
    quantity: 91,
    expiry: '2027-11',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 28,
    section: 'medicine-secondary',
    name: 'Hydralazine Injection',
    brand: 'Unknown',
    strength: '20mg/ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 60,
    expiry: '2027-05',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 29,
    section: 'medicine-secondary',
    name: 'Sodium Bicarbonate Injection',
    brand: 'Unknown',
    strength: '8.4% w/v',
    form: 'ampoule',
    route: 'IV',
    quantity: 100,
    expiry: '2028-03',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 30,
    section: 'medicine-secondary',
    name: 'Atropine Sulphate Injection',
    brand: 'Unknown',
    strength: '1.0mg/ml',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 75,
    expiry: '2028-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 31,
    section: 'medicine-secondary',
    name: 'Potassium Chloride Injection',
    brand: 'American Remedies',
    strength: '',
    form: 'ampoule',
    route: 'Injection',
    quantity: 50,
    expiry: '2028-08',
    category: 'prescription',
    requiresPrescription: true,
    needsReview: true,
    reviewNote: 'Strength was not visible; only brand and product family were legible.',
  },
  {
    lineNumber: 32,
    section: 'medicine-secondary',
    name: 'Dopamine Injection',
    brand: 'Unknown',
    strength: '200mg/5ml',
    form: 'ampoule',
    route: 'Injection',
    quantity: 60,
    expiry: '2028-03',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 33,
    section: 'medicine-secondary',
    name: 'Cefotaxime Injection',
    brand: 'Unknown',
    strength: '1000mg',
    form: 'vial',
    route: 'IM/IV',
    quantity: 4,
    expiry: '2026-08',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 34,
    section: 'medicine-secondary',
    name: 'Vitamin K1 Injection',
    brand: 'Unknown',
    strength: '10mg',
    form: 'ampoule',
    route: 'IM/IV',
    quantity: 40,
    expiry: '2028-05',
    category: 'vitamins',
    requiresPrescription: true,
  },
  {
    lineNumber: 35,
    section: 'medicine-secondary',
    name: 'Hydrocortisone Sodium Injection',
    brand: 'Unknown',
    strength: '1ml',
    form: 'vial',
    route: 'IV',
    quantity: 20,
    expiry: '2027-10',
    category: 'prescription',
    requiresPrescription: true,
    needsReview: true,
    reviewNote: 'Strength notation was recorded as 1ml/I.V in the notebook and may need confirmation.',
  },
  {
    lineNumber: 36,
    section: 'medicine-secondary',
    name: 'Meropenem Injection',
    brand: 'Unknown',
    strength: '1000mg',
    form: 'vial',
    route: 'IV',
    quantity: 2,
    expiry: '2027-04',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 37,
    section: 'medicine-secondary',
    name: 'Caffeine Citrate Injection',
    brand: 'Unknown',
    strength: '20mg',
    form: 'ampoule',
    route: 'IV',
    quantity: 5,
    expiry: '2027-03',
    category: 'prescription',
    requiresPrescription: true,
  },
  {
    lineNumber: 8,
    section: 'supplies-secondary',
    name: 'Chlorhexidine Gluconate',
    brand: 'Unknown',
    strength: '25g',
    unit: 'tube',
    route: 'Topical',
    quantity: 5,
    expiry: '2028-08',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 9,
    section: 'supplies-secondary',
    name: 'Aciclovir Cream',
    brand: 'Unknown',
    strength: '5% / 15g',
    unit: 'tube',
    route: 'Topical',
    quantity: 30,
    expiry: '2026-08',
    category: 'otc',
    requiresPrescription: false,
  },
  {
    lineNumber: 10,
    section: 'supplies-secondary',
    name: 'Nebuliser Prongs - Adult',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 329,
    expiry: '2029-02',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 11,
    section: 'supplies-secondary',
    name: 'Nebuliser Prongs - Child',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 100,
    expiry: '2029-05',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 12,
    section: 'supplies-secondary',
    name: 'H. Pylori Antibody RDT Cassette',
    brand: 'Ac-Care',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 79,
    expiry: '2030-08',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 13,
    section: 'supplies-secondary',
    name: 'H. Pylori Ab RDT Cassette',
    brand: 'Just Check',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 8,
    expiry: '2027-10',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was written as 7 + 1 and was normalized to 8.',
  },
  {
    lineNumber: 14,
    section: 'supplies-secondary',
    name: 'HCV RDT Strips',
    brand: 'Devmed',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 48,
    expiry: '2028-03',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 15,
    section: 'supplies-secondary',
    name: 'HCV Strips',
    brand: 'Nucuro Care',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 35,
    expiry: '2028-08',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was written as 33 + 2 and was normalized to 35.',
  },
  {
    lineNumber: 16,
    section: 'supplies-secondary',
    name: 'PSA Test Kits',
    brand: 'Sachet Check',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 7,
    expiry: '2028-02',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 17,
    section: 'supplies-secondary',
    name: 'HCG Cassette',
    brand: 'Invest Check',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 5,
    expiry: '2028-06',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Notebook includes the note 1/47 before Invest Check; brand text may need confirmation.',
  },
  {
    lineNumber: 18,
    section: 'supplies-secondary',
    name: 'HSV Cassette Kit',
    brand: 'Turbo Check',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 4,
    expiry: '2028-08',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 19,
    section: 'supplies-secondary',
    name: 'Nasal Prongs - Neonate',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 97,
    expiry: '2029-05',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 20,
    section: 'supplies-secondary',
    name: 'Chlamydia Test Kit Cassette',
    brand: 'Unknown',
    strength: 'Serum/Plasma',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 2,
    expiry: '2028-06',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 21,
    section: 'supplies-secondary',
    name: 'Malaria Test Kit Cassette',
    brand: 'SD Biosensor',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 7,
    expiry: '2027-10',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 22,
    section: 'supplies-secondary',
    name: 'HCG Strips',
    brand: 'Apex',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 7,
    expiry: '2028-09',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 22,
    section: 'supplies-secondary',
    name: 'HCG Strips',
    brand: 'Atox',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 2,
    expiry: '2027-03',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 23,
    section: 'supplies-secondary',
    name: 'Gonorrhea Rapid Test - Swab Cassette',
    brand: 'Unknown',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 4,
    expiry: '2029-08',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 24,
    section: 'supplies-secondary',
    name: 'HIV/Syphilis Combo Kits',
    brand: 'SD Biosensor / TOS Test Kits',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 1,
    expiry: '2025-04',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 25,
    section: 'supplies-secondary',
    name: 'Feeding Tube',
    brand: 'Unknown',
    strength: '12F',
    unit: 'piece',
    route: 'N/A',
    quantity: 1,
    expiry: '2028-12',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 26,
    section: 'supplies-secondary',
    name: 'Feeding Tube',
    brand: 'Unknown',
    strength: '12F',
    unit: 'piece',
    route: 'N/A',
    quantity: 124,
    expiry: '2030-06',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 27,
    section: 'supplies-secondary',
    name: 'Feeding Tube',
    brand: 'Unknown',
    strength: '8F',
    unit: 'piece',
    route: 'N/A',
    quantity: 242,
    expiry: '2029-10',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was written as 237 + 5 and was normalized to 242.',
  },
  {
    lineNumber: 28,
    section: 'supplies-secondary',
    name: 'URS-10A Urinalysis Strips',
    brand: 'Unknown',
    strength: '',
    unit: 'cup',
    route: 'Diagnostic',
    quantity: 28,
    expiry: '2028-10',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Unit was recorded as cups in the notebook.',
  },
  {
    lineNumber: 30,
    section: 'supplies-secondary',
    name: 'Uric Acid Test Strips',
    brand: 'Unknown',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 4,
    expiry: '2027-05',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 31,
    section: 'supplies-secondary',
    name: 'Cholesterol Test Strips',
    brand: 'Unknown',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 3,
    expiry: '2027-08',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 32,
    section: 'supplies-secondary',
    name: 'Feeding Tube',
    brand: 'Unknown',
    strength: '6F',
    unit: 'piece',
    route: 'N/A',
    quantity: 300,
    expiry: '2029-05',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 33,
    section: 'supplies-secondary',
    name: 'ACCU-ANSWER Strips',
    brand: 'ACCU-ANSWER',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 3,
    expiry: '2027-11',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 34,
    section: 'supplies-secondary',
    name: 'Catheter - Urine',
    brand: 'Unknown',
    strength: '22Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 50,
    expiry: '2027-10',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 35,
    section: 'supplies-secondary',
    name: 'Catheter - Urine',
    brand: 'Unknown',
    strength: '8Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 6,
    expiry: '2027-02',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 36,
    section: 'supplies-secondary',
    name: 'Catheter - Urine',
    brand: 'Unknown',
    strength: '14Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 10,
    expiry: '2030-09',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 37,
    section: 'supplies-secondary',
    name: 'Catheter - Urine',
    brand: 'Unknown',
    strength: '12Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 8,
    expiry: '2030-09',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 38,
    section: 'supplies-secondary',
    name: 'Catheter - Urine',
    brand: 'Unknown',
    strength: '16Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 9,
    expiry: '2029-12',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 39,
    section: 'supplies-secondary',
    name: 'Catheter - Urine',
    brand: 'Unknown',
    strength: '6Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 24,
    expiry: '2029-08',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 40,
    section: 'supplies-secondary',
    name: 'Suction Catheter',
    brand: 'Unknown',
    strength: '18F',
    unit: 'piece',
    route: 'N/A',
    quantity: 98,
    expiry: '2030-06',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 41,
    section: 'supplies-secondary',
    name: 'Blood Bag',
    brand: 'Unknown',
    strength: '250ml',
    unit: 'piece',
    route: 'N/A',
    quantity: 95,
    expiry: '2028-11',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 42,
    section: 'supplies-secondary',
    name: 'Suction Catheter',
    brand: 'Unknown',
    strength: '6',
    unit: 'piece',
    route: 'N/A',
    quantity: 98,
    expiry: '2030-12',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 43,
    section: 'supplies-secondary',
    name: 'Feeding Tube',
    brand: 'Unknown',
    strength: '10Fr',
    unit: 'piece',
    route: 'N/A',
    quantity: 22,
    expiry: '2028-03',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 44,
    section: 'supplies-secondary',
    name: 'Suture Vicryl - Round Bodied',
    brand: 'Unknown',
    strength: '2/0',
    unit: 'piece',
    route: 'N/A',
    quantity: 192,
    expiry: '2028-04',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 45,
    section: 'supplies-secondary',
    name: 'Mercurial Sphygmomanometer',
    brand: 'Unknown',
    strength: '',
    unit: 'device',
    route: 'N/A',
    quantity: 2,
    expiry: '2099-12',
    category: 'equipment',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used for equipment.',
  },
  {
    lineNumber: 46,
    section: 'supplies-secondary',
    name: 'Suture Vicryl - Round Bodied',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 12,
    expiry: '2028-04',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 47,
    section: 'supplies-secondary',
    name: 'Brown Bandage',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 7,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 48,
    section: 'supplies-secondary',
    name: 'Digital BP Monitor',
    brand: 'Don-V BK-5225',
    strength: '',
    unit: 'device',
    route: 'N/A',
    quantity: 1,
    expiry: '2099-12',
    category: 'equipment',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used for equipment.',
  },
  {
    lineNumber: 49,
    section: 'supplies-secondary',
    name: 'OMRON BP Monitor',
    brand: 'M1 Basic',
    strength: '',
    unit: 'device',
    route: 'N/A',
    quantity: 1,
    expiry: '2099-12',
    category: 'equipment',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used for equipment.',
  },
  {
    lineNumber: 50,
    section: 'supplies-secondary',
    name: 'Uni-Gold HIV',
    brand: 'Trinity Biotech',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 4,
    expiry: '2026-09',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 51,
    section: 'supplies-secondary',
    name: 'Soby Sex / Soby Set',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 2,
    expiry: '2028-06',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Item name is unclear in the notebook.',
  },
  {
    lineNumber: 52,
    section: 'supplies-secondary',
    name: 'Cord Clamp',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 98,
    expiry: '2029-04',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 53,
    section: 'supplies-secondary',
    name: 'HBU Test Kit',
    brand: 'Namo Care',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 29,
    expiry: '2028-12',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 54,
    section: 'supplies-secondary',
    name: 'HBU Test Kit',
    brand: 'First Check',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 4,
    expiry: '2028-08',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 55,
    section: 'supplies-secondary',
    name: 'ErbaQik Sickle Cell Test',
    brand: 'ErbaQik',
    strength: '',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 1,
    expiry: '2027-06',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 56,
    section: 'supplies-secondary',
    name: 'Amino Hook',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 200,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 57,
    section: 'supplies-secondary',
    name: 'HBsAg Strips',
    brand: 'Unknown',
    strength: '',
    unit: 'box',
    route: 'Diagnostic',
    quantity: 103,
    expiry: '2027-08',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was recorded as boxes and kept as boxes.',
  },
  {
    lineNumber: 58,
    section: 'supplies-secondary',
    name: 'HAV',
    brand: 'Namo Care',
    strength: '',
    unit: 'box',
    route: 'Diagnostic',
    quantity: 3,
    expiry: '2028-10',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was recorded as boxes and kept as boxes.',
  },
  {
    lineNumber: 59,
    section: 'supplies-secondary',
    name: 'HIV Strips',
    brand: 'Numo/Namo Care',
    strength: '',
    unit: 'box',
    route: 'Diagnostic',
    quantity: 43,
    expiry: '2028-12',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Brand spelling may be Numo or Namo Care; quantity was recorded as boxes.',
  },
  {
    lineNumber: 60,
    section: 'supplies-secondary',
    name: 'HIV Antigen RDT',
    brand: 'Numo/Namo Care',
    strength: '',
    unit: 'box',
    route: 'Diagnostic',
    quantity: 18,
    expiry: '2027-01',
    category: 'diagnostics',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was recorded as boxes/cassettes and normalized to 18.',
  },
  {
    lineNumber: 61,
    section: 'supplies-secondary',
    name: 'HCG',
    brand: 'Accu-Link',
    strength: '',
    unit: 'box',
    route: 'Diagnostic',
    quantity: 1,
    expiry: '2026-09',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 62,
    section: 'supplies-secondary',
    name: 'Syphilis Test Strips',
    brand: 'Unknown',
    strength: '',
    unit: 'strip',
    route: 'Diagnostic',
    quantity: 1,
    expiry: '2027-10',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 63,
    section: 'supplies-secondary',
    name: 'Nasal Prongs - Infant',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 70,
    expiry: '2028-03',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 64,
    section: 'supplies-secondary',
    name: 'Oxygen Mask - Child',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 45,
    expiry: '2028-03',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 65,
    section: 'supplies-secondary',
    name: 'Oxygen Mask - Adult Elongated',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 1,
    expiry: '2027-03',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 66,
    section: 'supplies-secondary',
    name: 'Oxygen Mask - Standard Paediatric',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 2,
    expiry: '2028-06',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 67,
    section: 'supplies-secondary',
    name: 'Chlamydia RDT',
    brand: 'Just Check',
    strength: 'Serum/Plasma',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 6,
    expiry: '2028-06',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 68,
    section: 'supplies-secondary',
    name: 'Chlamydia IgM Test Kits',
    brand: 'Gina',
    strength: 'Serum',
    unit: 'kit',
    route: 'Diagnostic',
    quantity: 6,
    expiry: '2027-08',
    category: 'diagnostics',
    requiresPrescription: false,
  },
  {
    lineNumber: 69,
    section: 'supplies-secondary',
    name: 'Air Compressing Nebulizer',
    brand: 'Unknown',
    strength: '',
    unit: 'device',
    route: 'N/A',
    quantity: 0,
    expiry: '2099-12',
    category: 'equipment',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Brand and quantity were unclear; placeholder quantity and expiry used for equipment.',
  },
  {
    lineNumber: 70,
    section: 'supplies-secondary',
    name: 'Compressor Nebulizer',
    brand: 'Curo/Curon',
    strength: '',
    unit: 'device',
    route: 'N/A',
    quantity: 1,
    expiry: '2099-12',
    category: 'equipment',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Brand spelling is unclear and no expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 71,
    section: 'supplies-secondary',
    name: 'Plain Tube / Pile Tube',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 150,
    expiry: '2027-07',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Item name is unclear in the notebook.',
  },
  {
    lineNumber: 72,
    section: 'supplies-secondary',
    name: 'Zinc Oxide Adhesive Plaster',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 5,
    expiry: '2028-02',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 73,
    section: 'supplies-secondary',
    name: 'Surgical Brush',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 1,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 74,
    section: 'supplies-secondary',
    name: 'Digital Thermometer',
    brand: 'Unknown',
    strength: '',
    unit: 'device',
    route: 'N/A',
    quantity: 3,
    expiry: '2099-12',
    category: 'equipment',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used for equipment.',
  },
  {
    lineNumber: 75,
    section: 'supplies-secondary',
    name: 'Cover Glass',
    brand: 'Unknown',
    strength: '24 x 50',
    unit: 'box',
    route: 'Laboratory',
    quantity: 18,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Quantity was recorded as boxes and no expiry was visible.',
  },
  {
    lineNumber: 76,
    section: 'supplies-secondary',
    name: 'Spinal Needle',
    brand: 'Unknown',
    strength: '23G',
    unit: 'piece',
    route: 'N/A',
    quantity: 35,
    expiry: '2027-10',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 77,
    section: 'supplies-secondary',
    name: 'Sterile Gauze Swabs',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 24,
    expiry: '2028-04',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 78,
    section: 'supplies-secondary',
    name: 'Vaseline Gauze',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 198,
    expiry: '2027-06',
    category: 'supplies',
    requiresPrescription: false,
  },
  {
    lineNumber: 79,
    section: 'supplies-secondary',
    name: 'Nurses Cap',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 600,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 80,
    section: 'supplies-secondary',
    name: 'Microscope Cover Glasses',
    brand: 'Unknown',
    strength: '22 x 22mm',
    unit: 'piece',
    route: 'Laboratory',
    quantity: 1000,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 81,
    section: 'supplies-secondary',
    name: 'Cryovial Tubes',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'Laboratory',
    quantity: 150,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'No expiry was recorded; placeholder expiry used.',
  },
  {
    lineNumber: 82,
    section: 'supplies-secondary',
    name: 'Dolo Ionic Gel',
    brand: 'Unknown',
    strength: '',
    unit: 'tube',
    route: 'Topical',
    quantity: 1,
    expiry: '2028-08',
    category: 'otc',
    requiresPrescription: false,
  },
  {
    lineNumber: 83,
    section: 'supplies-secondary',
    name: 'Unclear Item',
    brand: 'Unknown',
    strength: '',
    unit: 'piece',
    route: 'N/A',
    quantity: 4,
    expiry: '2099-12',
    category: 'supplies',
    requiresPrescription: false,
    needsReview: true,
    reviewNote: 'Item description and expiry were not clear in the image.',
  },
];

const asObjectId = (value: unknown): Types.ObjectId => {
  if (value instanceof Types.ObjectId) {
    return value;
  }

  return new Types.ObjectId(String(value));
};

const slug = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 32);

const toExpiryDate = (value: string) => {
  const [year, month] = value.split('-').map(Number);
  return new Date(Date.UTC(year, month - 1, 1));
};

const buildSku = (item: NotebookItem, importIndex: number) =>
  `NBK-${String(importIndex).padStart(2, '0')}-${slug(item.name)
    .replace(/-/g, '')
    .slice(0, 12)
    .toUpperCase()}`;

const buildBarcode = (_item: NotebookItem, importIndex: number) =>
  `990000${String(importIndex).padStart(4, '0')}`;

const unitForForm = (form?: NotebookItem['form']) => {
  if (!form) {
    return 'piece';
  }

  return form === 'vial' ? 'vial' : form;
};

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);

  try {
    const branchModel = app.get<Model<Branch>>(getModelToken(Branch.name));
    const productModel = app.get<Model<Product>>(getModelToken(Product.name));
    const supplierModel = app.get<Model<Supplier>>(getModelToken(Supplier.name));
    const batchModel = app.get<Model<Batch>>(getModelToken(Batch.name));
    const stockMovementModel = app.get<Model<StockMovement>>(
      getModelToken(StockMovement.name),
    );
    const userModel = app.get<Model<User>>(getModelToken(User.name));

    const branch = await branchModel.findOne({ code: 'HQ' }).lean();
    if (!branch) {
      throw new Error('HQ branch not found.');
    }

    const importUser =
      (await userModel.findOne({ username: 'hq_manager' }).lean()) ||
      (await userModel.findOne({ role: 'super_admin' }).lean());

    if (!importUser) {
      throw new Error('No import user found.');
    }

    const supplier = await supplierModel
      .findOneAndUpdate(
        { email: NOTEBOOK_IMPORT_SUPPLIER.email },
        NOTEBOOK_IMPORT_SUPPLIER,
        {
          returnDocument: 'after',
          upsert: true,
          setDefaultsOnInsert: true,
        },
      )
      .lean();

    const importedProducts: string[] = [];
    const reviewItems: Array<{ sku: string; note: string }> = [];

    for (const [index, item] of notebookItems.entries()) {
      const importIndex = index + 1;
      const sku = buildSku(item, importIndex);
      const barcode = buildBarcode(item, importIndex);
      const productName = `${item.name} ${item.strength}`.replace(/\s+/g, ' ').trim();
      const unit = item.unit ?? unitForForm(item.form);

      const product = await productModel
        .findOneAndUpdate(
          {
            branchId: asObjectId(branch._id),
            sku,
          },
          {
            branchId: asObjectId(branch._id),
            name: productName,
            sku,
            barcode,
            category: item.category,
            brand: item.brand,
            unit,
            reorderLevel: Math.max(1, Math.ceil(item.quantity * 0.2)),
            maxStockLevel: Math.max(item.quantity, 1),
            basePrice: 0,
            costPrice: 0,
            suggestedRetailPrice: 0,
            markupPercentage: 0,
            requiresPrescription: item.requiresPrescription,
            isControlled: false,
            isActive: true,
            packSizes: [],
          },
          {
            returnDocument: 'after',
            upsert: true,
            setDefaultsOnInsert: true,
          },
        )
        .lean();

      const batch = await batchModel
        .findOneAndUpdate(
          {
            branchId: asObjectId(branch._id),
            productId: asObjectId(product._id),
            lotNumber: `${sku}-LOT-01`,
          },
          {
            branchId: asObjectId(branch._id),
            productId: asObjectId(product._id),
            lotNumber: `${sku}-LOT-01`,
            expiryDate: toExpiryDate(item.expiry),
            quantityAvailable: item.quantity,
            quantityInitial: item.quantity,
            purchasePrice: 0,
            sellingPrice: 0,
            supplierId: asObjectId(supplier._id),
            isExpired: false,
            isDepleted: item.quantity <= 0,
          },
          {
            returnDocument: 'after',
            upsert: true,
            setDefaultsOnInsert: true,
          },
        )
        .lean();

      await stockMovementModel.deleteMany({
        'metadata.seedKey': `notebook:${sku}`,
      });

      await stockMovementModel.create({
        branchId: asObjectId(branch._id),
        productId: asObjectId(product._id),
        batchId: asObjectId(batch._id),
        quantity: item.quantity,
        movementType: MovementType.PURCHASE,
        reason: 'Manual notebook inventory import',
        userId: asObjectId(importUser._id),
        timestamp: new Date(),
        metadata: {
          seedKey: `notebook:${sku}`,
          source: 'notebook-images-2026-05-06',
          section: item.section,
          importIndex,
          lineNumber: item.lineNumber,
          strength: item.strength,
          route: item.route,
          needsReview: item.needsReview ?? false,
          reviewNote: item.reviewNote,
        },
      });

      importedProducts.push(sku);

      if (item.needsReview && item.reviewNote) {
        reviewItems.push({ sku, note: item.reviewNote });
      }
    }

    console.log(`Imported ${importedProducts.length} notebook products into HQ.`);
    console.log(`Products now in database: ${await productModel.countDocuments()}`);
    console.log(`Batches now in database: ${await batchModel.countDocuments()}`);
    console.log(
      `Stock movements now in database: ${await stockMovementModel.countDocuments()}`,
    );

    if (reviewItems.length > 0) {
      console.log('\nItems needing review:');
      for (const item of reviewItems) {
        console.log(`- ${item.sku}: ${item.note}`);
      }
    }
  } finally {
    await app.close();
  }
}

void bootstrap()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
